name: heart
description: Core code & features shared between projects.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  build_runner: ^2.4.8
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
dependencies:
  collection: ^1.18.0
  crypto: ^3.0.3
  freezed_annotation: ^2.4.1
  hydrated_bloc: ^10.1.1
  json_annotation: ^4.8.1
  rxdart: ^0.28.0
  synchronized: ^3.4.0
